Repository ylopez25/Tech-dive, pull requests merged in 2024-02, with the labels that each got.

#5 Adding templated Docs
  docs/ROADMAP.md
  docs/backend_routes.md
  docs/frontend_routes.md
  docs/images/key-dates-and-deadlines.png
  docs/planning.md
  docs/user_stories.md
Labels: documentation

#31 Fake api connection
  client/package-lock.json
  client/package.json
  client/src/App.js
  client/src/components/Navbar.js
  client/src/hooks/use-api.js
  client/src/index.css
  client/src/pages/Admin.js
  client/src/pages/Exams.js
  client/src/pages/Home.js
Labels: implementation, FrontEnd

#48 26 fe get one exam page feature 1
  client/src/App.css
  client/src/App.js
  client/src/components/ExamInfo.js
  client/src/components/ExamsList.js
  client/src/components/PatientInfo.js
  client/src/context/ExamContext.js
  client/src/index.css
  client/src/pages/ExamDetails.js
  client/src/pages/Exams.js
  docs/User_Stories.md
  docs/user_stories.md
Labels: implementation, FrontEnd

#68 ID is displaying on examdetails url
  client/src/App.js
  client/src/components/ExamInfo.js
  client/src/components/ExamsList.js
  client/src/components/PatientInfo.js
  client/src/pages/ExamDetails.js
  client/src/pages/ExamUpdate.js
  client/src/pages/PatientDetails.js
Labels: change

#69 Admin Page ( Delete, Create, Update Buttons )
  api/models/examModel.js
  client/src/App.css
  client/src/App.js
  client/src/components/ExamInfo.js
  client/src/components/ExamsList.js
  client/src/components/PatientInfo.js
  client/src/context/ExamContext.js
  client/src/index.css
  client/src/pages/Exams.js
  client/src/pages/PatientDetails.js
Labels: implementation, FrontEnd

#71 17 be get all exams associated with a patient
  api/.env
  api/controllers/exam-controller.js
  api/routes/exams.js
Labels: implementation, change, FrontEnd, BackEnd, addition

#76 17 be get all exams associated with a patient
  api/controllers/exam-controller.js
  api/routes/exams.js
Labels: change, FrontEnd, BackEnd, addition

#77 70 fe get all exames for one patient
  client/src/App.js
  client/src/components/ExamInfo.js
  client/src/components/ExamsList.js
  client/src/components/PatientInfo.js
  client/src/pages/PatientDetails.js
  docs/backend_routes.md
Labels: change, FrontEnd

#82 Added Json Files, resolved CLI alerts
  client/package-lock.json
  client/package.json
  client/src/pages/Admin.js
  client/src/pages/CreateExam.js
Labels: bug, FrontEnd

#85 Pre deploy sandbox
  api/controllers/exam-controller.js
  client/build/asset-manifest.json
  client/build/favicon.png
  client/build/index.html
  client/build/manifest.json
  client/build/robots.txt
  client/build/static/css/main.bd65265a.css
  client/build/static/css/main.bd65265a.css.map
  client/build/static/js/592.599f76a2.chunk.js
  client/build/static/js/592.599f76a2.chunk.js.map
  client/build/static/js/main.e34761fe.js
  client/build/static/js/main.e34761fe.js.LICENSE.txt
  client/build/static/js/main.e34761fe.js.map
  client/src/App.js
  client/src/components/ExamsList.js
  client/src/components/PatientInfo.js
  client/src/pages/Admin.js
  client/src/pages/CreateExam.js
  package-lock.json
Labels: bug, implementation, change, FrontEnd, removal, staging

#88 83 fe update exam
  client/src/App.js
  client/src/components/ExamUpdate.js
  client/src/components/PatientInfo.js
  client/src/pages/ExamUpdate.js
  client/src/pages/UpdateExam.js
Labels: implementation, FrontEnd, addition

#89 Closure for Create Exam, Text Input for Exam Type, etc..
  client/src/components/ExamUpdate.js
  client/src/components/Navbar.js
  client/src/components/logo.js
  client/src/pages/Admin.js
  client/src/pages/CreateExam.js
Labels: implementation, change, FrontEnd, removal, addition

#93 Create exam page overall css
  client/src/App.css
  client/src/App.js
  client/src/components/ExamCreate.js
  client/src/components/ExamDelete.js
  client/src/components/ExamInfo.js
  client/src/components/ExamUpdate.js
  client/src/components/PatientInfo.js
  client/src/index.css
  client/src/pages/Admin.js
  client/src/pages/CreateExam.js
  client/src/pages/ExamDetails.js
  client/src/pages/Exams.js
  client/src/pages/PatientDetails.js
Labels: change
